import { CONTROL_ENDPOINT, IMPACT, classifyControlFailure, expiryForPreset, requiresCriticalConfirmation, validateTransition } from "./core.js";
const $ = (selector) => document.querySelector(selector); let current = null;
const label = (value) => String(value).replaceAll(".", " › ").replaceAll(/([A-Z])/g, " $1");

function show(message, error = false) { const node = $("#alert"); node.textContent = message; node.classList.toggle("error", error); node.hidden = false; }
function render(payload) { current = payload.configuration; $("#revision").textContent = `Revision ${current.revision}`; const controls = $("#controls"); controls.replaceChildren(); for (const [id, value] of Object.entries(current.controls)) { const dt = document.createElement("dt"), dd = document.createElement("dd"); dt.textContent = label(id); dd.textContent = `${value.state}${value.expiresAt ? ` · expires ${new Date(value.expiresAt).toLocaleString()}` : ""}`; controls.append(dt, dd); } $("#propagation").textContent = "Public revision confirmation pending after any change."; }
async function refresh() { const response = await fetch(CONTROL_ENDPOINT, { credentials: "include", cache: "no-store", headers: { Accept: "application/json" } }); if (!response.ok || response.redirected) throw new Error(classifyControlFailure(response)); render(await response.json()); }
$("#control").addEventListener("change", () => { $("#impact").textContent = IMPACT[$("#control").value]; }); $("#control").dispatchEvent(new Event("change")); $("#refresh").addEventListener("click", () => refresh().catch((error) => show(error.message, true)));
$("#control-form").addEventListener("submit", async (event) => { event.preventDefault(); const state = $("#state").value, duration = $("#duration").value; const draft = { controlId: $("#control").value, state, reasonCode: $("#reason-code").value, operatorReason: $("#operator-reason").value, expiresAt: state === "enabled" ? undefined : expiryForPreset(duration), onExpiry: $("#expiry-behavior").value }; const errors = validateTransition(draft); if (Object.keys(errors).length) return show(Object.values(errors).join(" "), true); $("#confirm-copy").textContent = `${draft.controlId} will become ${draft.state}. Impact: ${IMPACT[draft.controlId]}.`; if (requiresCriticalConfirmation(draft.controlId, draft.state)) $("#confirm-copy").textContent += " This is a critical broad-scope disable."; $("#confirm").showModal(); if (await new Promise((resolve) => $("#confirm").addEventListener("close", () => resolve($("#confirm").returnValue === "confirm"), { once: true }))) { const response = await fetch(CONTROL_ENDPOINT, { method: "PATCH", credentials: "include", cache: "no-store", headers: { Accept: "application/json", "Content-Type": "application/json", "If-Match": current.revision }, body: JSON.stringify(draft) }); if (!response.ok || response.redirected) return show(classifyControlFailure(response), true); render(await response.json()); show("Control changed. Verify the public revision before declaring propagation complete."); } });
refresh().catch((error) => show(error.message, true));
