export const HEALTH_ENDPOINT = "/admin/service/admin/provider-health";
export const CATALOG_ENDPOINT = "/admin/service/admin/provider-catalog";
export const CATALOG_ROLES = ["Primary", "Secondary", "Standby", "Automatic Fallback", "Monitoring Only", "Internal Protection", "Disabled"];
export function formatDate(value, fallback = "Not available") { if (!value) return fallback; const date = new Date(value); return Number.isNaN(date.valueOf()) ? fallback : new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(date); }
export function statusLabel(value) { return ({ healthy: "Healthy", degraded: "Degraded", critical: "Critical", incident: "Incident" })[value] || "Unknown"; }
export function incidentScope(item) { if (item.incidentKind === "shared_provider") return "Shared provider incident"; if (item.incidentKind === "quality_gate") return "Publication quality gate"; if (item.incidentKind === "isolated") return "Isolated station failure"; return item.affectedBeachCount > 1 ? "Multiple beaches affected" : "Isolated station failure"; }
export function roleWarning(role) { if (role === "Automatic Fallback") return "This provider is labeled as an automatic fallback only. Actual failover must be implemented separately."; if (role === "Disabled") return "This label does not disable provider requests."; return ""; }
export function providerMatches(item, { search = "", category = "", role = "", status = "" } = {}) { const health = item.health?.status ?? "unknown"; const haystack = [item.displayName, item.provider, item.domain, item.category, item.role, item.description, ...(item.usedFor ?? [])].join(" ").toLowerCase(); const query = search.trim().toLowerCase(); if (query && !haystack.includes(query)) return false; if (category && item.category !== category) return false; if (role && item.role !== role) return false; if (status === "official" && !item.officialSource) return false; if (status === "incident" && !item.health?.activeIncidentId) return false; if (["healthy", "degraded"].includes(status) && health !== status) return false; return true; }
export function refreshFailureMessage(error) { const message = error instanceof Error ? error.message : ""; return /session|auth|401|403/i.test(message) ? message : "Could not refresh provider health. Your admin session may have expired or the service may be temporarily unreachable."; }
export function pollController({ refresh, documentRef = document, intervalMs = 60000, timers = globalThis }) { let timer = null; const stop = () => { if (timer !== null) timers.clearInterval(timer); timer = null; }; const start = () => { stop(); if (!documentRef.hidden) timer = timers.setInterval(refresh, intervalMs); }; const visibility = () => documentRef.hidden ? stop() : (refresh(), start()); documentRef.addEventListener("visibilitychange", visibility); start(); return { stop() { stop(); documentRef.removeEventListener("visibilitychange", visibility); }, isRunning: () => timer !== null }; }
