export const HEALTH_ENDPOINT = "/admin/service/admin/provider-health";
export const CATALOG_ENDPOINT = "/admin/service/admin/provider-catalog";
export const NOTIFICATIONS_ENDPOINT = "/admin/service/admin/provider-health/notifications";
export const CATALOG_ROLES = ["Primary", "Secondary", "Standby", "Automatic Fallback", "Monitoring Only", "Internal Protection", "Disabled"];
export { formatCentralTime as formatDate } from "../shared.js";
export function statusLabel(value) { return ({ healthy: "Healthy", degraded: "Degraded", critical: "Critical", incident: "Incident" })[value] || "Unknown"; }
export function ingestionModeLabel(value) { return ({ enabled: "Enabled", monitorOnly: "Monitor only", disabled: "Disabled", manualOnly: "Manual only", unmonitored: "Unmonitored", retired: "Retired" })[value] || "Unmonitored"; }
export function monitoringLabel(item = {}) { if (item.monitoringStatus === "ended") return "Monitoring ended"; if (item.excludedFromActiveTotals) return "Excluded from operational totals"; if (item.monitoringStatus === "monitoring") return "Intentionally monitored"; return "Operationally monitored"; }
export function diagnosticRows(value) { if (!value || typeof value !== "object") return []; const rows = [["HTTP status", value.httpStatus], ["Content type", value.contentType], ["Response bytes", value.responseBytes], ["Fetch duration", Number.isFinite(value.fetchDurationMs) ? `${value.fetchDurationMs} ms` : undefined], ["VEVENT component", value.componentIndex], ["Safe UID hash", value.uidHash], ["Field category", value.fieldCategory], ["VEVENT totals", Number.isFinite(value.totalVEventCount) ? `${value.validVEventCount ?? 0} valid · ${value.rejectedVEventCount ?? 0} rejected · ${value.totalVEventCount} total` : undefined]]; return rows.filter(([, item]) => item !== undefined && item !== null && item !== ""); }
export function incidentScope(item) { if (item.incidentKind === "shared_provider") return "Shared provider incident"; if (item.incidentKind === "quality_gate") return "Publication quality gate"; if (item.incidentKind === "isolated") return "Isolated station failure"; return item.affectedBeachCount > 1 ? "Multiple beaches affected" : "Isolated station failure"; }
export function incidentDuration(item, now = Date.now()) { const start = Date.parse(item.firstFailureAt); if (!Number.isFinite(start)) return "Not available"; const minutes = Math.max(0, Math.round((now - start) / 60000)); return minutes < 120 ? `${minutes} min` : minutes < 2880 ? `${Math.round(minutes / 60)} hr` : `${Math.round(minutes / 1440)} days`; }
export function incidentNotification(item, data, notifications) { const alert = (data.recentAlerts || []).find(entry => entry.provider === item.provider && entry.domain === item.domain); if (alert) return alert.capturedOnly === false || alert.deliveryState === "sent" ? "Email sent" : "Captured for preview; no email sent"; if (!notifications?.configuration?.enabled) return "Notifications disabled"; if (!notifications?.bindingReady) return "Configured, but delivery binding is not ready"; return "No matching delivery recorded"; }
export function roleWarning(role) { if (role === "Automatic Fallback") return "This provider is labeled as an automatic fallback only. Actual failover must be implemented separately."; if (role === "Disabled") return "This label does not disable provider requests."; return ""; }
export function providerMatches(item, { search = "", category = "", role = "", status = "" } = {}) { const health = item.health?.status ?? "unknown"; const haystack = [item.displayName, item.provider, item.domain, item.category, item.role, item.description, ...(item.usedFor ?? [])].join(" ").toLowerCase(); const query = search.trim().toLowerCase(); if (query && !haystack.includes(query)) return false; if (category && item.category !== category) return false; if (role && item.role !== role) return false; if (status === "official" && !item.officialSource) return false; if (status === "incident" && !item.health?.activeIncidentId) return false; if (["healthy", "degraded"].includes(status) && health !== status) return false; return true; }
export function refreshFailureMessage(error) { const message = error instanceof Error ? error.message : ""; return /session|auth|401|403/i.test(message) ? message : "Could not refresh provider health. Your admin session may have expired or the service may be temporarily unreachable."; }
export function notificationPayload({ enabled, recipients }) { return { enabled: Boolean(enabled), recipients: String(recipients || "").split(",").map((item) => item.trim()).filter(Boolean) }; }
export function metadataEditState(provider, domain) {
  let dirty = false, active = true;
  return { key: `${provider}:${domain}`, markDirty() { if (active) dirty = true; }, discard() { active = false; dirty = false; }, saved() { active = false; dirty = false; }, get dirty() { return active && dirty; }, get active() { return active; } };
}
export function pollController({ refresh, documentRef = document, intervalMs = 60000, timers = globalThis }) { let timer = null; const stop = () => { if (timer !== null) timers.clearInterval(timer); timer = null; }; const start = () => { stop(); if (!documentRef.hidden) timer = timers.setInterval(refresh, intervalMs); }; const visibility = () => documentRef.hidden ? stop() : (refresh(), start()); documentRef.addEventListener("visibilitychange", visibility); start(); return { stop() { stop(); documentRef.removeEventListener("visibilitychange", visibility); }, isRunning: () => timer !== null }; }
