import test from "node:test";
import assert from "node:assert/strict";
import { AREA_NAMES, DATASET_NAMES, OBSERVATIONS_ENDPOINT, SUMMARY_ENDPOINT, centralWallTimeToIso, chartPoints, chartSegments, failureMessage, formatTime, healthLabel, normalizeObservationFilters, observationQuery, timestampLabel } from "../admin/historical-data/core.js";
import fs from "node:fs";

test("uses protected read-only endpoints and bounded filter query", () => { assert.equal(SUMMARY_ENDPOINT, "/admin/service/admin/historical-data"); assert.equal(OBSERVATIONS_ENDPOINT, "/admin/service/admin/historical-data/observations"); const url=observationQuery({type:"water_temperature",area:"orangeBeach",pageSize:"25",provider:""},"cursor"); assert.match(url,/type=water_temperature/); assert.match(url,/cursor=cursor/); assert.doesNotMatch(url,/provider=/); });
test("renders textual health and timestamp semantics", () => { assert.equal(healthLabel("healthy"),"Healthy"); assert.equal(healthLabel("late"),"Stale"); assert.equal(timestampLabel({observation_time_basis:"predicted_event"}),"Predicted event"); assert.equal(timestampLabel({observation_time_basis:"sample_date"}),"Sample/result date"); });
test("formats Central timestamps without incompatible Intl shorthand options", () => { assert.match(formatTime("2026-08-09T01:24:00Z"), /Aug 8, 2026/); assert.match(formatTime("2026-08-09T01:24:00Z"), /CDT/); });
test("distinguishes Access expiry, unavailable service, and unconfigured D1", () => { assert.match(failureMessage({status:403}),/Access session/); assert.match(failureMessage({status:503,notConfigured:true}),/not configured/); assert.match(failureMessage({status:500}),/temporarily unavailable/); });
test("creates stable chart points and retains complete labels", () => { assert.equal(chartPoints([{inserted:0},{inserted:10}],100,50),"0,50 100,12"); assert.equal(Object.keys(AREA_NAMES).length,4); assert.equal(Object.keys(DATASET_NAMES).length,6); });
test("hourly charts preserve missing buckets as gaps", () => { assert.equal(chartSegments([{bucket:"2026-08-01T00:00:00Z",inserted:2},{bucket:"2026-08-01T01:00:00Z",inserted:3},{bucket:"2026-08-01T03:00:00Z",inserted:4}]).length,2); });
test("page includes one active Historical Data nav destination and responsive assets", () => { const html=fs.readFileSync(new URL("../admin/historical-data/index.html",import.meta.url),"utf8"); const nav=html.match(/<div class="nav-links"[^>]*>(.*?)<\/div>/)?.[1] || ""; assert.equal((nav.match(/>Historical Data<\/a>/g)||[]).length,1); assert.match(nav,/aria-current="page"[^>]*href="\.\/">Historical Data<\/a>/); assert.match(html,/noindex,nofollow,noarchive/); assert.match(html,/Current revisions/); assert.match(html,/id="previous"/); assert.match(html,/id="next"/); assert.match(html,/details-toggle|Details/); assert.match(html,/navigation\.js/); });
test("converts Central wall time independently and handles DST deliberately", () => { assert.equal(centralWallTimeToIso("2026-01-15T12:00"),"2026-01-15T18:00:00.000Z"); assert.equal(centralWallTimeToIso("2026-07-15T12:00"),"2026-07-15T17:00:00.000Z"); assert.throws(()=>centralWallTimeToIso("2026-03-08T02:30"),/does not exist/); assert.equal(centralWallTimeToIso("2026-11-01T01:30"),"2026-11-01T06:30:00.000Z"); assert.equal(centralWallTimeToIso("2026-11-01T01:30","later"),"2026-11-01T07:30:00.000Z"); });
test("validates filter ranges before requesting data", () => { assert.throws(()=>normalizeObservationFilters({observedFrom:"2026-08-02T10:00",observedTo:"2026-08-01T10:00",storedFrom:"",storedTo:""}),/From must be before/); assert.equal(normalizeObservationFilters({observedFrom:"2026-08-01T10:00",observedTo:"",storedFrom:"",storedTo:""}).observedFrom,"2026-08-01T15:00:00.000Z"); });
test("pagination is transactional, guarded, and clears stale request errors", () => { const source=fs.readFileSync(new URL("../admin/historical-data/historical-data.js",import.meta.url),"utf8"); assert.match(source,/if \(observationsLoading\) return false/); assert.match(source,/const data = await request\([\s\S]*if \(intent\.type === "next"\)/); assert.match(source,/byId\("error"\)\.hidden = true/); assert.match(source,/cursor:cursors\[page-1\]/); assert.doesNotMatch(source,/cursors\.push\(nextCursor\);page\+\+/); });
