import test from "node:test";
import assert from "node:assert/strict";
import { CATALOG_ENDPOINT, HEALTH_ENDPOINT, NOTIFICATIONS_ENDPOINT, incidentScope, notificationPayload, pollController, providerMatches, refreshFailureMessage, roleWarning, statusLabel } from "../admin/provider-health/core.js";

test("uses the protected same-origin endpoint and accessible status labels", () => { assert.equal(HEALTH_ENDPOINT, "/admin/service/admin/provider-health"); assert.equal(statusLabel("critical"), "Critical"); assert.equal(incidentScope({ incidentKind: "shared_provider" }), "Shared provider incident"); assert.equal(incidentScope({ incidentKind: "isolated" }), "Isolated station failure"); });
test("uses the protected metadata endpoint and keeps role warnings explicit", () => { assert.equal(CATALOG_ENDPOINT, "/admin/service/admin/provider-catalog"); assert.match(roleWarning("Automatic Fallback"), /failover must be implemented separately/); assert.match(roleWarning("Disabled"), /does not disable provider requests/); assert.equal(roleWarning("Primary"), ""); });
test("uses the protected provider-health notification endpoint", () => { assert.equal(NOTIFICATIONS_ENDPOINT, "/admin/service/admin/provider-health/notifications"); });
test("builds the provider-health notification update contract", () => { assert.deepEqual(notificationPayload({ enabled: true, recipients: " first@example.com, second@example.com " }), { enabled: true, recipients: ["first@example.com", "second@example.com"] }); assert.deepEqual(notificationPayload({ enabled: false, recipients: "" }), { enabled: false, recipients: [] }); });
test("provider health admin exposes email notification controls", async () => { const html = await import("node:fs/promises").then((fs) => fs.readFile(new URL("../admin/provider-health/index.html", import.meta.url), "utf8")); const js = await import("node:fs/promises").then((fs) => fs.readFile(new URL("../admin/provider-health/provider-health.js", import.meta.url), "utf8")); assert.match(html, /Provider Health Notifications/); assert.match(html, /id="notification-enabled"/); assert.match(html, /id="notification-recipients"/); assert.match(html, /Send test email/); assert.match(js, /method: "PATCH"/); assert.match(js, /NOTIFICATIONS_ENDPOINT.*test/); });
test("notification mutations prevent duplicate requests and preserve success feedback", async () => { const js = await import("node:fs/promises").then((fs) => fs.readFile(new URL("../admin/provider-health/provider-health.js", import.meta.url), "utf8")); assert.match(js, /if \(notificationMutation\) return/); assert.match(js, /refresh\(\{ preserveNotice: true \}\)/); assert.match(js, /showNotice\("Provider-health notification settings saved\."\)/); assert.match(js, /showNotice\("Provider-health test email sent\."\)/); });
test("searches and filters catalog metadata and health", () => { const item = { displayName: "NWS Hourly Forecast", provider: "nws", domain: "hourly_forecast", category: "Weather", role: "Primary", description: "Official forecast", usedFor: ["Weather verification"], officialSource: true, health: { status: "healthy" } }; assert.equal(providerMatches(item, { search: "verification" }), true); assert.equal(providerMatches(item, { category: "UV" }), false); assert.equal(providerMatches(item, { role: "Primary", status: "official" }), true); assert.equal(providerMatches(item, { status: "incident" }), false); });
test("classifies Access redirects that browsers surface as network failures", () => { assert.match(refreshFailureMessage(new TypeError("Failed to fetch")), /session may have expired/); assert.equal(refreshFailureMessage(new Error("Your admin session may have expired.")), "Your admin session may have expired."); });
test("polling pauses while hidden and refreshes when visible", () => { let hidden = false, listener, refreshes = 0, next = 0; const active = new Set(); const documentRef = { get hidden() { return hidden; }, addEventListener(_name, value) { listener = value; }, removeEventListener() {} }; const timers = { setInterval() { const id = ++next; active.add(id); return id; }, clearInterval(id) { active.delete(id); } }; const poll = pollController({ refresh: () => refreshes++, documentRef, timers }); assert.equal(poll.isRunning(), true); hidden = true; listener(); assert.equal(poll.isRunning(), false); hidden = false; listener(); assert.equal(refreshes, 1); assert.equal(poll.isRunning(), true); poll.stop(); assert.equal(active.size, 0); });
