import test from "node:test";
import assert from "node:assert/strict";
import { CATALOG_ENDPOINT, HEALTH_ENDPOINT, NOTIFICATIONS_ENDPOINT, diagnosticRows, incidentDuration, incidentNotification, incidentScope, ingestionModeLabel, metadataEditState, monitoringLabel, notificationPayload, pollController, providerMatches, refreshFailureMessage, roleWarning, statusLabel } from "../admin/provider-health/core.js";

test("uses the protected same-origin endpoint and accessible status labels", () => { assert.equal(HEALTH_ENDPOINT, "/admin/service/admin/provider-health"); assert.equal(statusLabel("critical"), "Critical"); assert.equal(incidentScope({ incidentKind: "shared_provider" }), "Shared provider incident"); assert.equal(incidentScope({ incidentKind: "isolated" }), "Isolated station failure"); });
test("incident timing and notification context use supported fields", () => { const item={provider:"nws",domain:"flags",firstFailureAt:"2026-08-01T00:00:00Z"}; assert.equal(incidentDuration(item,Date.parse("2026-08-01T03:00:00Z")),"3 hr"); assert.equal(incidentNotification(item,{recentAlerts:[{provider:"nws",domain:"flags",deliveryState:"sent"}]},{}),"Email sent"); assert.equal(incidentNotification(item,{recentAlerts:[]},{configuration:{enabled:false}}),"Notifications disabled"); });
test("uses the protected metadata endpoint and keeps role warnings explicit", () => { assert.equal(CATALOG_ENDPOINT, "/admin/service/admin/provider-catalog"); assert.match(roleWarning("Automatic Fallback"), /failover must be implemented separately/); assert.match(roleWarning("Disabled"), /does not disable provider requests/); assert.equal(roleWarning("Primary"), ""); });
test("uses the protected provider-health notification endpoint", () => { assert.equal(NOTIFICATIONS_ENDPOINT, "/admin/service/admin/provider-health/notifications"); });
test("renders every provider ingestion lifecycle without calling ended monitoring a recovery", () => { assert.deepEqual(["enabled", "monitorOnly", "disabled", "manualOnly", "unmonitored", "retired"].map(ingestionModeLabel), ["Enabled", "Monitor only", "Disabled", "Manual only", "Unmonitored", "Retired"]); assert.equal(monitoringLabel({ monitoringStatus: "ended" }), "Monitoring ended"); assert.equal(monitoringLabel({ excludedFromActiveTotals: true }), "Excluded from operational totals"); assert.equal(monitoringLabel({ monitoringStatus: "monitoring" }), "Intentionally monitored"); assert.equal(monitoringLabel({}), "Operationally monitored"); });
test("formats only bounded structured provider diagnostics", () => { assert.deepEqual(diagnosticRows({ httpStatus: 200, contentType: "text/calendar", responseBytes: 512, fetchDurationMs: 18, componentIndex: 3, uidHash: "deadbeef", fieldCategory: "dtstart_invalid", totalVEventCount: 4, validVEventCount: 2, rejectedVEventCount: 1 }), [["HTTP status", 200], ["Content type", "text/calendar"], ["Response bytes", 512], ["Fetch duration", "18 ms"], ["VEVENT component", 3], ["Safe UID hash", "deadbeef"], ["Field category", "dtstart_invalid"], ["VEVENT totals", "2 valid · 1 rejected · 4 total"]]); assert.deepEqual(diagnosticRows(null), []); });
test("builds the provider-health notification update contract", () => { assert.deepEqual(notificationPayload({ enabled: true, recipients: " first@example.com, second@example.com " }), { enabled: true, recipients: ["first@example.com", "second@example.com"] }); assert.deepEqual(notificationPayload({ enabled: false, recipients: "" }), { enabled: false, recipients: [] }); });
test("provider health admin exposes email notification controls", async () => { const html = await import("node:fs/promises").then((fs) => fs.readFile(new URL("../admin/provider-health/index.html", import.meta.url), "utf8")); const js = await import("node:fs/promises").then((fs) => fs.readFile(new URL("../admin/provider-health/provider-health.js", import.meta.url), "utf8")); assert.match(html, /Provider Health Notifications/); assert.match(html, /id="notification-enabled"/); assert.match(html, /id="notification-recipients"/); assert.match(html, /Send test email/); assert.match(js, /method: "PATCH"/); assert.match(js, /NOTIFICATIONS_ENDPOINT.*test/); });
test("notification mutations prevent duplicate requests and preserve success feedback", async () => { const js = await import("node:fs/promises").then((fs) => fs.readFile(new URL("../admin/provider-health/provider-health.js", import.meta.url), "utf8")); assert.match(js, /if \(notificationMutation\) return/); assert.match(js, /refresh\(\{ preserveNotice: true \}\)/); assert.match(js, /showNotice\("Provider-health notification settings saved\."\)/); assert.match(js, /showNotice\("Provider-health test email sent\."\)/); });
test("searches and filters catalog metadata and health", () => { const item = { displayName: "NWS Hourly Forecast", provider: "nws", domain: "hourly_forecast", category: "Weather", role: "Primary", description: "Official forecast", usedFor: ["Weather verification"], officialSource: true, health: { status: "healthy" } }; assert.equal(providerMatches(item, { search: "verification" }), true); assert.equal(providerMatches(item, { category: "UV" }), false); assert.equal(providerMatches(item, { role: "Primary", status: "official" }), true); assert.equal(providerMatches(item, { status: "incident" }), false); });
test("classifies Access redirects that browsers surface as network failures", () => { assert.match(refreshFailureMessage(new TypeError("Failed to fetch")), /session may have expired/); assert.equal(refreshFailureMessage(new Error("Your admin session may have expired.")), "Your admin session may have expired."); });
test("polling pauses while hidden and refreshes when visible", () => { let hidden = false, listener, refreshes = 0, next = 0; const active = new Set(); const documentRef = { get hidden() { return hidden; }, addEventListener(_name, value) { listener = value; }, removeEventListener() {} }; const timers = { setInterval() { const id = ++next; active.add(id); return id; }, clearInterval(id) { active.delete(id); } }; const poll = pollController({ refresh: () => refreshes++, documentRef, timers }); assert.equal(poll.isRunning(), true); hidden = true; listener(); assert.equal(poll.isRunning(), false); hidden = false; listener(); assert.equal(refreshes, 1); assert.equal(poll.isRunning(), true); poll.stop(); assert.equal(active.size, 0); });
test("metadata edit state preserves dirty drafts until save or intentional cancel", () => { const draft=metadataEditState("nws","forecast"); draft.markDirty(); assert.equal(draft.dirty,true); draft.saved(); assert.equal(draft.dirty,false); const canceled=metadataEditState("nws","forecast"); canceled.markDirty(); canceled.discard(); assert.equal(canceled.active,false); });
test("provider refresh paths guard the active metadata draft", async () => { const source=await import("node:fs/promises").then(fs=>fs.readFile(new URL("../admin/provider-health/provider-health.js",import.meta.url),"utf8")); assert.match(source,/activeMetadataEdit\?\.active/); assert.match(source,/activeMetadataEdit\.dirty/); assert.match(source,/Discard the unsaved provider metadata edit/); assert.match(source,/refresh\(\{ afterSave: true \}\)/); assert.match(source,/activeMetadataEdit\?\.discard/); });
test("provider cards explain mode, exclusions, ended monitoring, and diagnostics", async () => { const source=await import("node:fs/promises").then(fs=>fs.readFile(new URL("../admin/provider-health/provider-health.js",import.meta.url),"utf8")); assert.match(source,/Ingestion mode/); assert.match(source,/Included in active totals/); assert.match(source,/Monitoring ended \(not recovered\)/); assert.match(source,/historical incident preserved/); assert.match(source,/diagnosticRows\(health\?\.diagnostics\)/); });
