import test from "node:test";
import assert from "node:assert/strict";
import { VERIFICATION_ENDPOINT, failureMessage, formatDuration, historyMatches, pollController, statusLabel } from "../admin/verification/core.js";

const item = { status: "fail", slot: "2026-07-21T12", reason: "published result differs", locations: [{ name: "Gulf Shores Public Beach", message: "Flag mismatch" }], checks: [{ message: "purple advisory mismatch" }] };
test("uses the protected same-origin verification endpoint and textual statuses", () => { assert.equal(VERIFICATION_ENDPOINT, "/admin/service/admin/verification"); assert.equal(statusLabel("pass"), "Passing"); assert.equal(statusLabel("warning"), "Warning"); assert.equal(statusLabel("fail"), "Failed"); assert.equal(statusLabel("unavailable"), "Unavailable"); });
test("formats duration and filters history by status and searchable report detail", () => { assert.equal(formatDuration(480), "480 ms"); assert.equal(formatDuration(1500), "1.5 sec"); assert.equal(historyMatches(item, { status: "fail", search: "public beach" }), true); assert.equal(historyMatches(item, { status: "pass" }), false); assert.equal(historyMatches(item, { search: "purple" }), true); });
test("distinguishes Access-session responses from temporary API failures", () => { assert.match(failureMessage({ status: 403, contentType: "application/json" }), /Access session/); assert.match(failureMessage({ status: 500, contentType: "application/json" }), /last successful state/); assert.match(failureMessage({ network: true }), /Access session/); });
test("polling pauses while hidden and refreshes once on return", () => { let hidden = false, listener, calls = 0, next = 0; const active = new Set(); const documentRef = { get hidden() { return hidden; }, addEventListener(_name, value) { listener = value; }, removeEventListener() {} }; const timers = { setInterval() { const id = ++next; active.add(id); return id; }, clearInterval(id) { active.delete(id); } }; const poll = pollController({ refresh: () => calls++, documentRef, timers }); assert.equal(poll.isRunning(), true); hidden = true; listener(); assert.equal(poll.isRunning(), false); hidden = false; listener(); assert.equal(calls, 1); assert.equal(poll.isRunning(), true); poll.stop(); assert.equal(active.size, 0); });
