import{requestJson,setNotice,formatCentralTime}from"../shared.js";import{ENDPOINT,CATEGORY_LABELS,STATUS_LABELS,matchesReport,terminalStatus,updatePayload}from"./core.js";
const $=s=>document.querySelector(s);let reports=[],selected=null,history=[],changing=false;const text=(tag,value,className="")=>{const node=document.createElement(tag);node.textContent=value;if(className)node.className=className;return node};
function addOptions(select,values,labels={}){for(const value of values){const option=document.createElement("option");option.value=value;option.textContent=labels[value]||value;select.append(option)}}
function currentFilters(){return{search:$("#search").value,status:$("#status").value,category:$("#category").value,beach:$("#beach").value}}
function render(){const visible=reports.filter(item=>matchesReport(item,currentFilters()));$("#reports").replaceChildren(...visible.map(card));$("#count").textContent=`${visible.length} report${visible.length===1?"":"s"}${reports.filter(r=>r.status==="new").length?` · ${reports.filter(r=>r.status==="new").length} new`:""}`;if(!visible.length)$("#reports").append(text("div","No reports match these filters.","empty"));}
function card(report){const button=text("button","","report-card");button.type="button";button.append(text("span",STATUS_LABELS[report.status]||report.status,"status-pill"),text("h2",report.contextTitle||CATEGORY_LABELS[report.category]||"Information report"));const meta=text("div","","report-meta");[CATEGORY_LABELS[report.category],report.beachId,formatCentralTime(report.receivedAt)].filter(Boolean).forEach(v=>meta.append(text("span",v)));button.append(meta,text("p",report.message,"report-preview"));button.addEventListener("click",()=>open(report.id));return button}
function definition(report){const dl=text("dl","","technical");const pairs=[["Status",STATUS_LABELS[report.status]],["Category",CATEGORY_LABELS[report.category]],["Submitted",formatCentralTime(report.receivedAt)],["Client created",formatCentralTime(report.clientCreatedAt)],["Contact email",report.contactEmail||"Not provided"],["Report ID",report.id],["Client report ID",report.clientReportId],["Beach/region ID",report.beachId],["Access ID",report.beachAccessId],["Map POI ID",report.mapPoiId],["Source ID",report.sourceId],["Learn article ID",report.learnArticleId],["Screen",report.screenId],["App",`${report.appVersion} (${report.appBuild})`],["Catalog",report.catalogVersion]];for(const[label,value]of pairs){if(value){dl.append(text("dt",label),text("dd",value))}}return dl}
function renderDetail(){$("#detail-title").textContent=selected.contextTitle||"Information report";const body=$("#detail-body");body.replaceChildren(text("p",selected.message,"message"),definition(selected));const heading=text("h3","Audit history"),list=text("ol","","history");for(const item of history)list.append(text("li",`${formatCentralTime(item.createdAt)} — ${item.action}${item.toStatus?` → ${STATUS_LABELS[item.toStatus]||item.toStatus}`:""} (${item.actor})`));body.append(heading,list);$("#resolution-note").value=selected.resolutionNote||"";$("#duplicate-id").value=selected.duplicateOfReportId||"";$("#duplicate-field").hidden=selected.status!=="duplicate";setNotice($("#detail-notice"),"")}
async function open(id){try{const data=await requestJson(`${ENDPOINT}/${encodeURIComponent(id)}`);selected=data.report;history=data.history||[];renderDetail();if(!$("#detail").open)$("#detail").showModal()}catch(error){setNotice($("#notice"),error.message,{kind:"error"})}}
async function change(status){if(changing||!selected)return;if(status==="duplicate"&&!$("#duplicate-id").value.trim()){$("#duplicate-field").hidden=false;$("#duplicate-id").focus();setNotice($("#detail-notice"),"Enter the report ID this duplicates before marking it duplicate.",{kind:"error"});return}if(terminalStatus(status)&&!confirm(`Confirm ${STATUS_LABELS[status].toLowerCase()} status? This report remains in the private audit queue.`))return;changing=true;document.querySelectorAll("[data-status]").forEach(button=>button.disabled=true);setNotice($("#detail-notice"),"Saving…");try{const data=await requestJson(`${ENDPOINT}/${encodeURIComponent(selected.id)}`,{method:"PATCH",body:JSON.stringify(updatePayload(status,$("#resolution-note").value,$("#duplicate-id").value))});selected=data.report;reports=reports.map(r=>r.id===selected.id?selected:r);render();const detail=await requestJson(`${ENDPOINT}/${encodeURIComponent(selected.id)}`);selected=detail.report;history=detail.history||[];renderDetail();setNotice($("#detail-notice"),"Status saved.")}catch(error){setNotice($("#detail-notice"),error.message,{kind:"error"})}finally{changing=false;document.querySelectorAll("[data-status]").forEach(button=>button.disabled=false)}}
async function load(){setNotice($("#notice"),"");$("#loading").hidden=false;try{const data=await requestJson(ENDPOINT);reports=data.reports||[];const beaches=[...new Set(reports.map(r=>r.beachId).filter(Boolean))].sort();$("#beach").replaceChildren(new Option("All beaches",""));addOptions($("#beach"),beaches);render();const requested=new URLSearchParams(location.search).get("report");if(requested)await open(requested)}catch(error){setNotice($("#notice"),error.message,{kind:"error"})}finally{$("#loading").hidden=true}}
addOptions($("#status"),Object.keys(STATUS_LABELS),STATUS_LABELS);addOptions($("#category"),Object.keys(CATEGORY_LABELS),CATEGORY_LABELS);$("#filters").addEventListener("input",render);$("#refresh").addEventListener("click",load);document.querySelectorAll("[data-status]").forEach(button=>button.addEventListener("click",()=>change(button.dataset.status)));$("#copy").addEventListener("click",async()=>{await navigator.clipboard.writeText(`${selected.id}\n${CATEGORY_LABELS[selected.category]}\n${selected.message}`);setNotice($("#detail-notice"),"Report details copied.")});load();
