import { EVENT_TYPES as TYPES, IMPACT_LEVELS as IMPACTS, refreshEmptyState, statusSummary, validateEventDraft } from "./core.js";
const API = "/admin/service";
const $ = (selector) => document.querySelector(selector);
const labels = {pendingReview:"Pending Review",raceOrSport:"Race or sport",beachCleanup:"Beach cleanup",fireworksOrHoliday:"Fireworks or holiday",accessOrParkingImpact:"Access or parking impact"};
let model = {events:[],rules:[],providers:[],beaches:[],beachReferences:[],audit:[],exclusions:[],coverage:[],refresh:null,notifications:null};
let refreshLoadError = "";
const escDate = value => new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(value));
const localValue = value => value ? new Date(new Date(value).getTime()-new Date(value).getTimezoneOffset()*60000).toISOString().slice(0,16) : "";

function notify(message,error=false){const box=$("#alert");box.textContent=message;box.hidden=false;box.classList.toggle("error",error)}
async function request(path,options={}){const response=await fetch(`${API}${path}`,{credentials:"include",headers:{Accept:"application/json",...(options.body?{"Content-Type":"application/json"}:{})},...options});if(!response.ok){const payload=await response.json().catch(()=>null),fields=payload?.fields?.length?` Check: ${payload.fields.join(", ")}.`:"";throw new Error(`${payload?.error||`Request failed (${response.status})`}${fields}`)}return response.json()}
function text(tag,value,className){const node=document.createElement(tag);node.textContent=value;if(className)node.className=className;return node}
function statusCounts(){return statusSummary(model.events)}
function renderStats(){const counts=statusCounts(),refresh=model.refresh?.counts||{},activeBeaches=model.coverage.filter(item=>item.activeEvents>0).length;$("#stats").replaceChildren(...[["Provider health",(model.refresh?.providers||[]).filter(item=>item.status==="ok").length],["Raw events",refresh.raw||0],["Exact matches",refresh.matched||0],["Needs review",counts.pendingReview||0],["Published",counts.published||0],["Excluded",model.exclusions.length],["Rule-suppressed",refresh.ruleSuppressed||0],["Active beaches",activeBeaches]].map(([label,value])=>{const node=text("div","", "stat");node.append(text("strong",String(value)),text("span",label));return node}))}
function refreshItem(label,value){const node=text("div","", "refresh-item");node.append(text("span",label),text("strong",value??"—"));return node}
function renderRefresh(){const refresh=model.refresh;$("#refresh-summary").textContent=refreshLoadError||refreshEmptyState(refresh);if(!refresh){$("#refresh-details").replaceChildren();$("#provider-refresh").replaceChildren();return}const age=refresh.lastSuccess?`${Math.max(0,Math.floor((Date.now()-Date.parse(refresh.lastSuccess))/60000))} min`:"Never";$("#refresh-details").replaceChildren(refreshItem("Overall",refresh.status),refreshItem("Last success",refresh.lastSuccess?escDate(refresh.lastSuccess):"Never"),refreshItem("Next scheduled",escDate(refresh.nextScheduledRefresh)),refreshItem("Data age",age),refreshItem("Operational control",refresh.operationalState),refreshItem("Stale cache",refresh.staleCache?"Yes":"No"));const filter=$("#provider-filter")?.value;$("#provider-refresh").replaceChildren(...(refresh.providers||[]).filter(provider=>!filter||provider.status===filter).map(provider=>{const config=model.providers.find(item=>item.id===provider.providerId)||{},card=text("article","", "provider-card");card.append(text("span",config.authority||"Provider","authority-badge"),text("strong",`${config.name||provider.providerId} · ${provider.status}`),text("p",`${config.mode||"enabled"} · ${config.feedType||"feed"} · ${config.cadence||"schedule unavailable"}`),text("p",`Raw ${provider.fetched} · matched ${provider.matched} · excluded ${provider.excluded} · pending ${provider.pendingReview} · published ${provider.published||0}`),text("p",provider.lastSuccess?`Last success ${escDate(provider.lastSuccess)} · ${provider.freshness}`:"Never successfully refreshed"));if(provider.error)card.append(text("p",provider.error,"reason"));return card}))}
function renderNotifications(){const data=model.notifications;if(!data)return;const config=data.configuration||{},state=data.state||{};$("#notification-enabled").checked=Boolean(config.enabled);$("#notification-daily").checked=Boolean(config.dailyReminder);$("#notification-immediate").checked=Boolean(config.immediateChangeNotification);$("#notification-time").value=config.reminderTime||"07:15";$("#notification-recipients").value=(config.recipients||[]).join(", ");$("#notification-status").textContent=!data.bindingReady?"Email binding unavailable":config.enabled?"Enabled":"Disabled";$("#notification-details").replaceChildren(...[["Last notification",state.lastNotificationAt?escDate(state.lastNotificationAt):"Never"],["Last reminder",state.lastReminderAt?escDate(state.lastReminderAt):"Never"],["Last success",state.lastSuccessAt?escDate(state.lastSuccessAt):"Never"],["Last failure",state.lastFailureAt?escDate(state.lastFailureAt):"None"],["Queue revision",state.lastQueueRevision||"None"],["Pending count",String(state.lastPendingCount||0)],["Duplicate suppression",`${state.suppressedDuplicateCount||0} suppressed`],["Last provider error",state.lastProviderError||"None"]].map(([label,value])=>refreshItem(label,value)))}
function filtered(){const status=$("#status-filter").value,q=$("#search").value.trim().toLowerCase();if(status==="excluded")return model.exclusions.filter(item=>!q||`${item.title} ${item.venue} ${item.sourceName} ${item.reasonDetail}`.toLowerCase().includes(q));return model.events.filter(event=>(!status||event.status===status)&&(!q||`${event.title} ${event.venue} ${event.sourceName}`.toLowerCase().includes(q)))}
function button(label,action,primary=false){const node=text("button",label,`button ${primary?"primary":"secondary"}`);node.type="button";node.addEventListener("click",action);return node}
function renderEvents(){const events=filtered(),root=$("#events"),excluded=$("#status-filter").value==="excluded";root.replaceChildren();$("#count").textContent=`${events.length} ${excluded?"candidate":"event"}${events.length===1?"":"s"}`;if(!events.length){root.append(text("p",excluded?"No excluded candidates match this view.":"No scheduled beach activity identified in this view.","empty"));return}for(const event of events){if(excluded){root.append(excludedCard(event));continue}const row=text("article","", "event-row"),body=document.createElement("div"),actions=text("div","", "event-actions");body.append(text("p",labels[event.status]||event.status,"eyebrow"),text("h3",event.title));const meta=text("div","", "event-meta");[escDate(event.startAt),event.venue,event.sourceName].forEach(v=>meta.append(text("span",v)));body.append(meta);const suggestions=text("div","", "event-suggestions");suggestions.append(text("span",labels[event.eventType]||event.eventType,"pill"),text("span",event.impactLevel,"pill"),text("span",`${event.matchConfidence} · ${event.matchMethod}`,"pill"));body.append(suggestions);actions.append(button("Review",()=>openReview(event),true),button("Edit",()=>openForm(event)));if(event.status==="pendingReview")actions.append(button("Approve",()=>updateEvent(event.id,{status:"approved"})),button("Disregard",()=>updateEvent(event.id,{status:"disregarded"})));if(["approved","scheduled"].includes(event.status))actions.append(button("Publish",()=>updateEvent(event.id,{status:"published"})));if(event.status==="published")actions.append(button("Unpublish",()=>updateEvent(event.id,{status:"hidden"})));row.append(body,actions);root.append(row)}}
function excludedCard(candidate){const row=text("article","", "event-row excluded-row"),body=document.createElement("div"),actions=text("div","", "event-actions");body.append(text("p","Excluded candidate","eyebrow"),text("h3",candidate.title),text("p",candidate.reasonDetail,"reason"));const meta=text("div","", "event-meta");[escDate(candidate.startAt),candidate.venue||"No venue",candidate.address||"No address",candidate.sourceName].forEach(v=>meta.append(text("span",v)));body.append(meta,text("p",`Rule: ${candidate.ruleId} · ${candidate.decision} · confidence ${candidate.matchConfidence}`,"muted"));const link=text("a","Open source","button secondary");link.href=candidate.sourceURL;link.target="_blank";link.rel="noopener noreferrer";actions.append(button("Assign to beach",()=>assignCandidate(candidate),true));if(candidate.venue)actions.append(button("Create venue alias",()=>createAlias(candidate,"venue")));if(candidate.address)actions.append(button("Create address alias",()=>createAlias(candidate,"address")));actions.append(link);row.append(body,actions);return row}
function renderCoverage(){const root=$("#coverage");root.replaceChildren(...model.coverage.map(item=>{const card=text("article","", "coverage-card");card.append(text("h3",item.beachName),text("span",item.coverageState==="active"?"Enabled source coverage":item.coverageState==="partial"?"Provider coverage is partial":"No active provider coverage","provider-state"),text("p",`${item.activeEvents} active event${item.activeEvents===1?"":"s"} · ${item.pendingCandidates} pending candidate${item.pendingCandidates===1?"":"s"}`),text("p",item.upcomingHighImpact?`Upcoming high impact: ${item.upcomingHighImpact.title}`:"No matching high-impact event found"));return card}))}
function render(){renderRefresh();renderNotifications();renderStats();renderCoverage();renderEvents()}
async function load(){try{model=await request("/admin/beach-events");refreshLoadError="";render();populateBeaches();renderRules()}catch(error){refreshLoadError="Refresh status unavailable";renderRefresh();notify(error.message,true)}}
async function updateEvent(id,changes){try{await request(`/admin/beach-events/${encodeURIComponent(id)}`,{method:"PATCH",body:JSON.stringify(changes)});notify("Event updated.");await load()}catch(error){notify(error.message,true)}}
async function refreshSources(){const control=$("#refresh-sources");control.disabled=true;control.textContent="Refreshing…";notify("Refreshing official event sources…");try{const result=await request("/internal/refresh/beach-events",{method:"POST"});if(result.outcome==="duplicate")notify("A source refresh is already running.");else if(result.outcome==="disabled")notify("Beach event ingestion is disabled.",true);else if(result.outcome==="failed")notify("Provider refresh failed.",true);else notify(result.outcome==="partial"?"Refresh completed with a provider warning.":"Event sources refreshed.");await load()}catch(error){notify(error.message,true)}finally{control.disabled=false;control.textContent="Refresh event sources"}}
async function saveNotifications(event){event.preventDefault();const control=$("#save-notifications");control.disabled=true;try{await request("/admin/beach-events/notifications",{method:"PATCH",body:JSON.stringify({enabled:$("#notification-enabled").checked,dailyReminder:$("#notification-daily").checked,immediateChangeNotification:$("#notification-immediate").checked,reminderTime:$("#notification-time").value,recipients:$("#notification-recipients").value.split(",").map(value=>value.trim()).filter(Boolean)})});notify("Notification settings saved.");await load()}catch(error){notify(error.message,true)}finally{control.disabled=false}}
async function sendNotification(kind){const control=$(kind==="test"?"#send-notification-test":"#send-review-summary");control.disabled=true;try{await request(`/admin/beach-events/notifications/${kind==="test"?"test":"send"}`,{method:"POST"});notify(kind==="test"?"Test email sent.":"Review summary sent.");await load()}catch(error){notify(error.message,true)}finally{control.disabled=false}}
function populateBeaches(){$("#beach").replaceChildren(...model.beaches.map(beach=>{const option=text("option",beach.displayName);option.value=beach.id;return option}))}
function populateVenueSuggestions(){const selected=$("#beach").value,names={["gulf-state-park-pavilion"]:["Gulf State Park Beach Pavilion","Beach Pavilion"],["dauphin-island-public-beach"]:["Dauphin Island Public Beach","Dauphin Island Middle Beach"],["dauphin-island-east-end"]:["Dauphin Island East End Beach","East End Beach"],["fort-morgan-public-beach"]:["Fort Morgan Public Beach","Fort Morgan Beach Access"],["cotton-bayou"]:["Cotton Bayou Public Beach"],["alabama-point"]:["Alabama Point East"]};$("#venue-suggestions").replaceChildren(...(names[selected]||[]).map(value=>{const option=document.createElement("option");option.value=value;return option}))}
function renderBeachReference(container,beachId){const reference=model.beachReferences.find(item=>item.id===beachId);container.replaceChildren();if(!reference){container.append(text("p","No configured beach reference is available.","muted"));return}const list=text("dl","", "reference-grid"),values=[["Canonical beach",`${reference.canonicalName} (${reference.id})`],["Area",reference.area],["Address",reference.address||"No verified address recorded"],["Coordinates",`${reference.coordinates.latitude}, ${reference.coordinates.longitude}`],["Venue aliases",reference.venueAliases.join("; ")||"None"],["Address aliases",reference.addressAliases.join("; ")||"None"],["Known exclusions",reference.excludedVenues.join("; ")||"None"],["Access notes",reference.accessNotes],["Flag source",reference.sources.flags],["Weather",reference.sources.weather],["Water quality",reference.sources.waterQuality],["Water temperature",reference.sources.waterTemperature.join("; ")||"Unavailable"],["Tide",reference.sources.tide||"Unavailable"],["Rip current",reference.sources.ripCurrent||"Unavailable"],["Event coverage",reference.sources.events.map(item=>`${item.name} (${item.mode})`).join("; ")||"None"],["Limitations",reference.limitations.join(" ")||"None recorded"],["Exact matching",reference.exactLocationNote]];values.forEach(([label,value])=>list.append(detail(label,value)));container.append(list)}
function updateFormBeachReference(){const target=$("#form-beach-reference [data-reference-content]");if(target)renderBeachReference(target,$("#beach").value)}
function updateBannerPreview(){const title=$("#banner-title").value.trim()||"Banner title",message=$("#banner-message").value.trim()||"Banner message",start=$("#start").value;$("#banner-preview").textContent=`Preview · ${title} — ${message}${start?` · Displays in Central Time beginning ${start}`:""}`}
function openForm(event=null){$("#event-form").reset();$("#event-id").value=event?.id||"";$("#form-title").textContent=event?"Edit event":"Create event";$("#title").value=event?.title||"";$("#beach").value=event?.beachId||model.beaches[0]?.id||"";$("#venue").value=event?.venue||"";$("#address").value=event?.address||"";$("#start").value=localValue(event?.startAt||new Date(Date.now()+3600000));$("#end").value=localValue(event?.endAt||new Date(Date.now()+7200000));$("#all-day").checked=event?.allDay||false;$("#event-type").value=event?.eventType||"community";$("#impact").value=event?.impactLevel||"informational";$("#source").value=event?.sourceName||"";$("#url").value=event?.sourceURL||"";$("#banner-title").value=event?.bannerTitle||"Community event here today";$("#banner-message").value=event?.bannerMessage||"An activity is scheduled at this beach.";["parking","traffic","access","compare"].forEach(key=>{$(`#${key}`).checked=event?.[`${key==="compare"?"showCompareNearbyBeaches":key+"Impact"}`]||false});$("#night-before").checked=Boolean(event?.displayFrom&&Date.parse(event.startAt)-Date.parse(event.displayFrom)>=8*3600000);$("#publish-status").value=event?.status||"draft";$("#display-from").value=localValue(event?.displayFrom);$("#notes").value=event?.internalNotes||"";populateVenueSuggestions();updateFormBeachReference();updateBannerPreview();$("#event-dialog").showModal()}
function eventPayload(){const start=new Date($("#start").value),display=$("#display-from").value;return{title:$("#title").value,beachId:$("#beach").value,venue:$("#venue").value,address:$("#address").value,startAt:start.toISOString(),endAt:new Date($("#end").value).toISOString(),allDay:$("#all-day").checked,eventType:$("#event-type").value,impactLevel:$("#impact").value,sourceName:$("#source").value,sourceURL:$("#url").value,bannerTitle:$("#banner-title").value,bannerMessage:$("#banner-message").value,parkingImpact:$("#parking").checked,trafficImpact:$("#traffic").checked,accessImpact:$("#access").checked,showCompareNearbyBeaches:$("#compare").checked,displayFrom:display?new Date(display).toISOString():$("#night-before").checked?new Date(start.getTime()-12*3600000).toISOString():undefined,status:$("#publish-status").value,internalNotes:$("#notes").value}}
function detail(label,value){const box=text("dl","", "review-card");box.append(text("dt",label),text("dd",value||"—"));return box}
function openReview(event){const root=$("#review-content");root.replaceChildren();const heading=text("div","", "dialog-heading"),titles=document.createElement("div");titles.append(text("p",labels[event.status]||event.status,"eyebrow"),text("h2",event.title));heading.append(titles,button("Close",()=>$("#review-dialog").close()));const scroll=text("div","", "review-scroll"),grid=text("div","", "review-grid");[["Date & time",event.endTimeUnavailable?`${escDate(event.startAt)} · End time not listed`:`${escDate(event.startAt)} – ${escDate(event.endAt)}`],["Description",event.eventDescription],["Contact or registration",event.contactInformation],["Newsletter issue",event.sourceNewsletterMonth],["Source",event.sourceName],["Source note",event.sourceNote],["Venue",event.venue],["Address",event.address],["Suggested beach",model.beaches.find(b=>b.id===event.beachId)?.displayName||event.beachId],["Match",`${event.matchConfidence} · ${event.matchMethod}`],["Event type",labels[event.eventType]||event.eventType],["Impact level",event.impactLevel],["Proposed banner",`${event.bannerTitle} — ${event.bannerMessage}`],["Recurring",event.recurring?"Yes":"No"],["Internal notes",event.internalNotes],["Similar decisions",similar(event)]].forEach(([a,b])=>grid.append(detail(a,b)));scroll.append(grid);const reference=document.createElement("details");reference.className="beach-reference";reference.append(text("summary","Beach reference"));const referenceContent=document.createElement("div");renderBeachReference(referenceContent,event.beachId);reference.append(referenceContent);scroll.append(reference);const link=text("a","View original source","source-link");link.href=event.sourceURL;link.target="_blank";link.rel="noopener noreferrer";scroll.append(link);const actions=text("div","", "review-actions"),secondary=document.createElement("details");secondary.className="secondary-actions";secondary.append(text("summary","More review actions"));const secondaryButtons=text("div","", "secondary-action-buttons");secondaryButtons.append(button("Disregard occurrence",()=>reviewAction(event,{status:"disregarded"})),button("Always disregard similar",()=>createRule(event,"disregard")),button("Mark not at a beach",()=>reviewAction(event,{status:"disregarded",internalNotes:"Administrator marked this occurrence as not physically at a supported beach."})),button("Auto-approve similar",()=>createRule(event,"autoApprove")),button("Cancel event",()=>reviewAction(event,{status:"cancelled"})));secondary.append(secondaryButtons);actions.append(button("Approve",()=>reviewAction(event,{status:"approved"}),true),button("Approve and edit",()=>{$("#review-dialog").close();openForm({...event,status:"approved"})}),secondary);root.append(heading,scroll,actions);$("#review-dialog").showModal()}
function similar(event){const matches=model.events.filter(item=>item.id!==event.id&&(item.venue===event.venue||item.title===event.title)).slice(0,3);return matches.length?matches.map(item=>`${item.title} (${labels[item.status]||item.status})`).join("; "):"No similar prior decisions"}
async function reviewAction(event,changes){await updateEvent(event.id,changes);$("#review-dialog").close()}
async function createRule(event,action){try{await request("/admin/beach-events/rules",{method:"POST",body:JSON.stringify({action,providerId:event.sourceFacts.providerId,venue:event.venue,titlePattern:action==="disregard"?event.title:undefined,beachId:event.beachId})});notify("Decision rule created.");$("#review-dialog").close();await load()}catch(error){notify(error.message,true)}}
function openAssignment(candidate,kind){$("#assignment-candidate").value=candidate.id;$("#assignment-kind").value=kind;$("#assignment-title").textContent=kind==="assign"?"Assign candidate":`Create ${kind} alias`;$("#assignment-help").textContent=kind==="assign"?"Assignment creates a pending-review event. It never publishes directly.":`This exact ${kind} will assign future candidates to the selected beach, while retaining pending review.`;$("#assignment-beach").replaceChildren(...model.beaches.map(beach=>{const option=text("option",beach.displayName);option.value=beach.id;return option}));$("#assignment-dialog").showModal()}
async function assignCandidate(candidate){openAssignment(candidate,"assign")}
async function createAlias(candidate,kind){openAssignment(candidate,kind)}
function renderRules(){const root=$("#rules"),q=$("#rule-search")?.value.trim().toLowerCase()||"",rules=model.rules.filter(rule=>!q||`${rule.action} ${rule.providerId} ${rule.venue||""} ${rule.address||""} ${rule.titlePattern||""}`.toLowerCase().includes(q));root.replaceChildren(...rules.map(rule=>detail(rule.action,`${rule.providerId} · ${rule.venue||rule.address||rule.titlePattern} · ${rule.beachId||"no beach"} · ${rule.enabled?"enabled":"disabled"}`)));if(!rules.length)root.append(text("p","No decision rules match this view.","empty"))}

TYPES.forEach(value=>{const option=text("option",labels[value]||value);option.value=value;$("#event-type").append(option)});IMPACTS.forEach(value=>{const option=text("option",value);option.value=value;$("#impact").append(option)});
$("#event-form").addEventListener("submit",async event=>{event.preventDefault();const save=$("#save-event");if(save.disabled)return;const id=$("#event-id").value,payload=eventPayload(),errors=validateEventDraft(payload);if(Object.keys(errors).length){notify(Object.values(errors).join(" "),true);return}save.disabled=true;save.textContent="Saving…";try{await request(id?`/admin/beach-events/${encodeURIComponent(id)}`:"/admin/beach-events",{method:id?"PATCH":"POST",body:JSON.stringify(payload)});$("#event-dialog").close();notify(id?"Event saved.":"Event created for review.");await load()}catch(error){notify(error.message,true)}finally{save.disabled=false;save.textContent="Save event"}});
$("#assignment-form").addEventListener("submit",async event=>{event.preventDefault();const id=$("#assignment-candidate").value,kind=$("#assignment-kind").value,beachId=$("#assignment-beach").value,candidate=model.exclusions.find(item=>item.id===id);if(!candidate)return;try{if(kind==="assign")await request(`/admin/beach-events/exclusions/${encodeURIComponent(id)}`,{method:"POST",body:JSON.stringify({beachId})});else await request("/admin/beach-events/rules",{method:"POST",body:JSON.stringify({action:"suggest",providerId:candidate.providerId,beachId,[kind]:candidate[kind]})});$("#assignment-dialog").close();notify(kind==="assign"?"Candidate assigned and placed in pending review.":`${kind==="venue"?"Venue":"Address"} alias created; future matches remain pending review.`);await load()}catch(error){notify(error.message,true)}});
$("#new-event").addEventListener("click",()=>openForm());$("#refresh-sources").addEventListener("click",refreshSources);$("#refresh").addEventListener("click",load);$("#notification-form").addEventListener("submit",saveNotifications);$("#send-notification-test").addEventListener("click",()=>sendNotification("test"));$("#send-review-summary").addEventListener("click",()=>sendNotification("manual"));$("#status-filter").addEventListener("change",renderEvents);$("#provider-filter").addEventListener("change",renderRefresh);$("#search").addEventListener("input",renderEvents);$("#rule-search").addEventListener("input",renderRules);$("#beach").addEventListener("change",()=>{populateVenueSuggestions();updateFormBeachReference()});["banner-title","banner-message","start"].forEach(id=>$("#"+id).addEventListener("input",updateBannerPreview));$("#rules-button").addEventListener("click",()=>$("#rules-dialog").showModal());document.querySelectorAll("[data-close]").forEach(node=>node.addEventListener("click",()=>node.closest("dialog").close()));load();
