import { EVENT_TYPES as TYPES, IMPACT_LEVELS as IMPACTS, refreshEmptyState, statusSummary, validateEventDraft } from "./core.js";
const API = "/admin/service";
const $ = (selector) => document.querySelector(selector);
const labels = {pendingReview:"Pending Review",raceOrSport:"Race or sport",beachCleanup:"Beach cleanup",fireworksOrHoliday:"Fireworks or holiday",accessOrParkingImpact:"Access or parking impact"};
let model = {events:[],rules:[],providers:[],beaches:[],audit:[],refresh:null};
let refreshLoadError = "";
const escDate = value => new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(value));
const localValue = value => value ? new Date(new Date(value).getTime()-new Date(value).getTimezoneOffset()*60000).toISOString().slice(0,16) : "";

function notify(message,error=false){const box=$("#alert");box.textContent=message;box.hidden=false;box.classList.toggle("error",error)}
async function request(path,options={}){const response=await fetch(`${API}${path}`,{credentials:"include",headers:{Accept:"application/json",...(options.body?{"Content-Type":"application/json"}:{})},...options});if(!response.ok)throw new Error((await response.json().catch(()=>null))?.error||`Request failed (${response.status})`);return response.json()}
function text(tag,value,className){const node=document.createElement(tag);node.textContent=value;if(className)node.className=className;return node}
function statusCounts(){return statusSummary(model.events)}
function renderStats(){const counts=statusCounts();$("#stats").replaceChildren(...[["pendingReview","Pending review"],["published","Published"],["scheduled","Scheduled"],["disregarded","Disregarded"]].map(([key,label])=>{const node=text("div","", "stat");node.append(text("strong",String(counts[key]||0)),text("span",label));return node}))}
function refreshItem(label,value){const node=text("div","", "refresh-item");node.append(text("span",label),text("strong",value??"—"));return node}
function renderRefresh(){const refresh=model.refresh;$("#refresh-summary").textContent=refreshLoadError||refreshEmptyState(refresh);if(!refresh){$("#refresh-details").replaceChildren();$("#provider-refresh").replaceChildren();return}const age=refresh.lastSuccess?`${Math.max(0,Math.floor((Date.now()-Date.parse(refresh.lastSuccess))/60000))} min`:"Never";$("#refresh-details").replaceChildren(refreshItem("Overall",refresh.status),refreshItem("Last attempt",refresh.lastAttempt?escDate(refresh.lastAttempt):"Never"),refreshItem("Last success",refresh.lastSuccess?escDate(refresh.lastSuccess):"Never"),refreshItem("Last failure",refresh.lastFailure?escDate(refresh.lastFailure):"None"),refreshItem("Next scheduled",escDate(refresh.nextScheduledRefresh)),refreshItem("Schedule",refresh.scheduleDescription),refreshItem("Data age",age),refreshItem("Operational control",refresh.operationalState),refreshItem("Raw",String(refresh.counts?.raw??0)),refreshItem("Exact matches",String(refresh.counts?.matched??0)),refreshItem("Excluded",String(refresh.counts?.excluded??0)),refreshItem("Pending review",String(refresh.counts?.pendingReview??0)),refreshItem("Published",String(refresh.counts?.published??0)),refreshItem("Rule-suppressed",String(refresh.counts?.ruleSuppressed??0)),refreshItem("Unsupported / ambiguous",String(refresh.counts?.unsupportedOrAmbiguous??0)),refreshItem("Stale cache",refresh.staleCache?"Yes":"No"));$("#provider-refresh").replaceChildren(...(refresh.providers||[]).map(provider=>{const card=text("article","", "provider-card"),name=model.providers.find(item=>item.id===provider.providerId)?.name||provider.providerId;card.append(text("span","Provider"),text("strong",`${name} · ${provider.status}`),text("p",`Raw ${provider.fetched} · matched ${provider.matched} · excluded ${provider.excluded} · pending ${provider.pendingReview} · suppressed ${provider.ruleSuppressed}${provider.error?` · ${provider.error}`:""}`));return card}))}
function filtered(){const status=$("#status-filter").value,q=$("#search").value.trim().toLowerCase();return model.events.filter(event=>(!status||event.status===status)&&(!q||`${event.title} ${event.venue} ${event.sourceName}`.toLowerCase().includes(q)))}
function button(label,action,primary=false){const node=text("button",label,`button ${primary?"primary":"secondary"}`);node.type="button";node.addEventListener("click",action);return node}
function renderEvents(){const events=filtered(),root=$("#events");root.replaceChildren();$("#count").textContent=`${events.length} event${events.length===1?"":"s"}`;if(!events.length){root.append(text("p","No events match this view.","empty"));return}for(const event of events){const row=text("article","", "event-row"),body=document.createElement("div"),actions=text("div","", "event-actions");body.append(text("p",labels[event.status]||event.status,"eyebrow"),text("h3",event.title));const meta=text("div","", "event-meta");[escDate(event.startAt),event.venue,event.sourceName].forEach(v=>meta.append(text("span",v)));body.append(meta);const suggestions=text("div","", "event-suggestions");suggestions.append(text("span",labels[event.eventType]||event.eventType,"pill"),text("span",event.impactLevel,"pill"),text("span",`${event.matchConfidence} · ${event.matchMethod}`,"pill"));body.append(suggestions);actions.append(button("Review",()=>openReview(event),true),button("Edit",()=>openForm(event)));if(event.status==="pendingReview")actions.append(button("Approve",()=>updateEvent(event.id,{status:"approved"})),button("Disregard",()=>updateEvent(event.id,{status:"disregarded"})));if(["approved","scheduled"].includes(event.status))actions.append(button("Publish",()=>updateEvent(event.id,{status:"published"})));if(event.status==="published")actions.append(button("Unpublish",()=>updateEvent(event.id,{status:"hidden"})));row.append(body,actions);root.append(row)}}
function render(){renderRefresh();renderStats();renderEvents()}
async function load(){try{model=await request("/admin/beach-events");refreshLoadError="";render();populateBeaches();renderRules()}catch(error){refreshLoadError="Refresh status unavailable";renderRefresh();notify(error.message,true)}}
async function updateEvent(id,changes){try{await request(`/admin/beach-events/${encodeURIComponent(id)}`,{method:"PATCH",body:JSON.stringify(changes)});notify("Event updated.");await load()}catch(error){notify(error.message,true)}}
async function refreshSources(){const control=$("#refresh-sources");control.disabled=true;control.textContent="Refreshing…";notify("Refreshing official event sources…");try{const result=await request("/internal/refresh/beach-events",{method:"POST"});if(result.outcome==="duplicate")notify("A source refresh is already running.");else if(result.outcome==="disabled")notify("Beach event ingestion is disabled.",true);else if(result.outcome==="failed")notify("Provider refresh failed.",true);else notify(result.outcome==="partial"?"Refresh completed with a provider warning.":"Event sources refreshed.");await load()}catch(error){notify(error.message,true)}finally{control.disabled=false;control.textContent="Refresh event sources"}}
function populateBeaches(){$("#beach").replaceChildren(...model.beaches.map(beach=>{const option=text("option",beach.displayName);option.value=beach.id;return option}))}
function openForm(event=null){$("#event-form").reset();$("#event-id").value=event?.id||"";$("#form-title").textContent=event?"Edit event":"Create event";$("#title").value=event?.title||"";$("#beach").value=event?.beachId||model.beaches[0]?.id||"";$("#venue").value=event?.venue||"";$("#address").value=event?.address||"";$("#start").value=localValue(event?.startAt||new Date(Date.now()+3600000));$("#end").value=localValue(event?.endAt||new Date(Date.now()+7200000));$("#all-day").checked=event?.allDay||false;$("#event-type").value=event?.eventType||"community";$("#impact").value=event?.impactLevel||"informational";$("#source").value=event?.sourceName||"";$("#url").value=event?.sourceURL||"";$("#banner-title").value=event?.bannerTitle||"Community event here today";$("#banner-message").value=event?.bannerMessage||"An activity is scheduled at this beach.";["parking","traffic","access","compare"].forEach(key=>{$(`#${key}`).checked=event?.[`${key==="compare"?"showCompareNearbyBeaches":key+"Impact"}`]||false});$("#night-before").checked=Boolean(event?.displayFrom&&Date.parse(event.startAt)-Date.parse(event.displayFrom)>=8*3600000);$("#publish-status").value=event?.status||"draft";$("#display-from").value=localValue(event?.displayFrom);$("#notes").value=event?.internalNotes||"";$("#event-dialog").showModal()}
function eventPayload(){const start=new Date($("#start").value),display=$("#display-from").value;return{title:$("#title").value,beachId:$("#beach").value,venue:$("#venue").value,address:$("#address").value,startAt:start.toISOString(),endAt:new Date($("#end").value).toISOString(),allDay:$("#all-day").checked,eventType:$("#event-type").value,impactLevel:$("#impact").value,sourceName:$("#source").value,sourceURL:$("#url").value,bannerTitle:$("#banner-title").value,bannerMessage:$("#banner-message").value,parkingImpact:$("#parking").checked,trafficImpact:$("#traffic").checked,accessImpact:$("#access").checked,showCompareNearbyBeaches:$("#compare").checked,displayFrom:display?new Date(display).toISOString():$("#night-before").checked?new Date(start.getTime()-12*3600000).toISOString():undefined,status:$("#publish-status").value,internalNotes:$("#notes").value}}
function detail(label,value){const box=text("dl","", "review-card");box.append(text("dt",label),text("dd",value||"—"));return box}
function openReview(event){const root=$("#review-content");root.replaceChildren();const heading=text("div","", "dialog-heading"),titles=document.createElement("div");titles.append(text("p",labels[event.status]||event.status,"eyebrow"),text("h2",event.title));heading.append(titles,button("Close",()=>$("#review-dialog").close()));root.append(heading);const grid=text("div","", "review-grid");[["Date & time",`${escDate(event.startAt)} – ${escDate(event.endAt)}`],["Source",event.sourceName],["Venue",event.venue],["Address",event.address],["Suggested beach",model.beaches.find(b=>b.id===event.beachId)?.displayName||event.beachId],["Match",`${event.matchConfidence} · ${event.matchMethod}`],["Event type",labels[event.eventType]||event.eventType],["Impact level",event.impactLevel],["Proposed banner",`${event.bannerTitle} — ${event.bannerMessage}`],["Recurring",event.recurring?"Yes":"No"],["Internal notes",event.internalNotes],["Similar decisions",similar(event)]].forEach(([a,b])=>grid.append(detail(a,b)));root.append(grid);const link=text("a","View original source","source-link");link.href=event.sourceURL;link.target="_blank";link.rel="noopener noreferrer";root.append(link);const actions=text("div","", "dialog-actions");actions.append(button("Approve",()=>reviewAction(event,{status:"approved"}),true),button("Approve and edit",()=>{$("#review-dialog").close();openForm({...event,status:"approved"})}),button("Disregard occurrence",()=>reviewAction(event,{status:"disregarded"})),button("Always disregard similar",()=>createRule(event,"disregard")),button("Mark not at a beach",()=>reviewAction(event,{status:"disregarded",internalNotes:"Administrator marked this occurrence as not physically at a supported beach."})),button("Auto-approve similar",()=>createRule(event,"autoApprove")),button("Cancel event",()=>reviewAction(event,{status:"cancelled"})));root.append(actions);$("#review-dialog").showModal()}
function similar(event){const matches=model.events.filter(item=>item.id!==event.id&&(item.venue===event.venue||item.title===event.title)).slice(0,3);return matches.length?matches.map(item=>`${item.title} (${labels[item.status]||item.status})`).join("; "):"No similar prior decisions"}
async function reviewAction(event,changes){await updateEvent(event.id,changes);$("#review-dialog").close()}
async function createRule(event,action){try{await request("/admin/beach-events/rules",{method:"POST",body:JSON.stringify({action,providerId:event.sourceFacts.providerId,venue:event.venue,titlePattern:action==="disregard"?event.title:undefined,beachId:event.beachId})});notify("Decision rule created.");$("#review-dialog").close();await load()}catch(error){notify(error.message,true)}}
function renderRules(){const root=$("#rules");root.replaceChildren(...model.rules.map(rule=>detail(rule.action,`${rule.providerId} · ${rule.venue||rule.titlePattern} · ${rule.beachId||"no beach"}`)));if(!model.rules.length)root.append(text("p","No decision rules yet.","empty"))}

TYPES.forEach(value=>{const option=text("option",labels[value]||value);option.value=value;$("#event-type").append(option)});IMPACTS.forEach(value=>{const option=text("option",value);option.value=value;$("#impact").append(option)});
$("#event-form").addEventListener("submit",async event=>{event.preventDefault();const id=$("#event-id").value,payload=eventPayload(),errors=validateEventDraft(payload);if(Object.keys(errors).length){notify(Object.values(errors).join(" "),true);return}try{await request(id?`/admin/beach-events/${encodeURIComponent(id)}`:"/admin/beach-events",{method:id?"PATCH":"POST",body:JSON.stringify(payload)});$("#event-dialog").close();notify(id?"Event saved.":"Event created for review.");await load()}catch(error){notify(error.message,true)}});
$("#new-event").addEventListener("click",()=>openForm());$("#refresh-sources").addEventListener("click",refreshSources);$("#refresh").addEventListener("click",load);$("#status-filter").addEventListener("change",renderEvents);$("#search").addEventListener("input",renderEvents);$("#rules-button").addEventListener("click",()=>$("#rules-dialog").showModal());document.querySelectorAll("[data-close]").forEach(node=>node.addEventListener("click",()=>node.closest("dialog").close()));load();
