import { AREA_NAMES, DATASET_NAMES, SUMMARY_ENDPOINT, chartPoints, failureMessage, formatCount, formatTime, healthLabel, observationQuery, timestampLabel } from "./core.js";
const byId = id => document.getElementById(id); let controller; let cursors = [null]; let page = 0; let nextCursor = null;
const escape = value => String(value ?? "").replace(/[&<>"']/g, character => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;", "'":"&#39;" })[character]);
const metric = (label, value) => `<div><dt>${label}</dt><dd>${value}</dd></div>`;
const number = value => formatCount(value);
const requestJson = async (url, signal) => { const response = await fetch(url, { credentials: "same-origin", headers: { Accept: "application/json" }, signal }); const type = response.headers.get("content-type") || ""; if (!response.ok || !type.includes("json")) { let body = {}; try { body = await response.json(); } catch {} throw new Error(failureMessage({ status: response.status, redirected: response.redirected, contentType: type, notConfigured: body.status === "not_configured" })); } return response.json(); };
function formValues() { return Object.fromEntries(new FormData(byId("filters")).entries().map(([key,value]) => [key, value && (key.endsWith("From") || key.endsWith("To")) ? new Date(value).toISOString() : value])); }

function renderSummary(data) {
  byId("updated").textContent = `Updated ${formatTime(data.generatedAt)}`; byId("overall").textContent = data.status === "ok" ? "Healthy" : "Needs attention"; byId("overall").className = `status-pill ${data.status === "ok" ? "healthy" : "late"}`;
  const s = data.summary || {}, daily = (data.last24Hours || []).reduce((a,r) => ({ inserted:a.inserted+Number(r.inserted||0), duplicates:a.duplicates+Number(r.duplicates||0), rejected:a.rejected+Number(r.rejected||0) }), {inserted:0,duplicates:0,rejected:0});
  byId("overview").innerHTML = metric("Environment", escape(data.environment)) + metric("Configured", data.configured ? "Yes" : "No") + metric("Beach-attributed rows", number(s.beach_attributed_rows)) + metric("Logical observations", number(s.logical_observations)) + metric("Unique physical observations", number(s.unique_physical_source_observations)) + metric("Revisions", number(s.revision_count)) + metric("Earliest stored", formatTime(s.earliest_stored_at)) + metric("Latest stored", formatTime(s.latest_stored_at)) + metric("Earliest source time", formatTime(s.earliest_observed_at)) + metric("Latest source/prediction time", formatTime(s.latest_observed_at)) + metric("Inserted · 24h", number(daily.inserted)) + metric("Duplicates ignored · 24h", number(daily.duplicates)) + metric("Rejected · 24h", number(daily.rejected));
  byId("jobs").innerHTML = (data.jobHealth || []).map(j => `<article class="health-card"><span class="status-pill ${escape(j.status)}">${healthLabel(j.status)}</span><h3>${escape(j.job)}</h3><dl><dt>Expected cadence</dt><dd>${j.cadenceMinutes} min</dd><dt>Last attempt</dt><dd>${formatTime(j.last_attempt_at)}</dd><dt>Last success</dt><dd>${formatTime(j.last_success_at)}</dd><dt>Last failure</dt><dd>${formatTime(j.last_failure_at)}</dd><dt>Since success</dt><dd>${j.ageMinutesSinceSuccess == null ? "Unavailable" : `${j.ageMinutesSinceSuccess} min`}</dd><dt>Attempted / inserted</dt><dd>${number(j.lifetime_attempted)} / ${number(j.lifetime_inserted)}</dd><dt>Duplicates / rejected</dt><dd>${number(j.lifetime_duplicates)} / ${number(j.lifetime_rejected)}</dd></dl></article>`).join("");
  byId("datasets").innerHTML = (data.datasets || []).map(d => `<tr><td><strong>${escape(DATASET_NAMES[d.observation_type] || d.observation_type)}</strong></td><td>${escape(d.provider)}</td><td>${number(d.station_count)}</td><td>${number(d.beach_count)} / ${number(d.area_count)}</td><td>${number(d.beach_attributed_rows)}</td><td>${number(d.unique_physical_source_observations)}</td><td>${number(Number(d.beach_attributed_rows)-Number(d.logical_observations))}</td><td>${formatTime(d.earliest_observed_at)}<br>${formatTime(d.latest_observed_at)}</td><td>${formatTime(d.latest_stored_at)}</td></tr>`).join("") || `<tr><td colspan="9">No historical datasets are stored yet.</td></tr>`;
  const areas = new Map((data.areas || []).map(a => [a.beach_area,a])); byId("areas").innerHTML = Object.entries(AREA_NAMES).map(([id,name]) => { const a=areas.get(id); return `<article class="area-card"><h3>${name}</h3>${a ? `<dl><dt>Datasets</dt><dd>${number(a.dataset_count)}</dd><dt>Beaches</dt><dd>${number(a.beach_count)}</dd><dt>Providers / stations</dt><dd>${number(a.provider_count)} / ${number(a.station_count)}</dd><dt>Latest stored</dt><dd>${formatTime(a.latest_stored_at)}</dd></dl>` : `<p class="note">No historical datasets represented.</p>`}</article>`; }).join("");
  byId("volume-line").setAttribute("points", chartPoints(data.insertVolume || [])); const total=(data.insertVolume||[]).reduce((n,r)=>n+Number(r.inserted||0),0); byId("volume-summary").textContent = `${number(total)} rows inserted across ${(data.insertVolume||[]).length} hourly buckets. Empty periods remain visible as zero volume.`;
  byId("runs").innerHTML = (data.recentRuns || []).slice(0,15).map(r => `<article class="run"><div><strong>${escape(r.job)}</strong><p>${formatTime(r.stored_at)} · attempted ${number(r.attempted_count)}, inserted ${number(r.inserted_count)}, duplicates ${number(r.duplicate_count)}, rejected ${number(r.rejected_count)}</p></div><span class="status-pill ${r.status === "failed" ? "failed" : "healthy"}">${escape(r.status)}${r.error_code ? ` · ${escape(r.error_code)}`:""}</span></article>`).join("") || `<p class="note">No ingestion runs recorded.</p>`;
  const alerts=[]; for(const j of data.jobHealth||[]) if(["late","never_succeeded"].includes(j.status)) alerts.push(`${j.job}: ${healthLabel(j.status)} (threshold ${j.maximumSuccessAgeMinutes} minutes).`); for(const r of data.recentFailures||[]) alerts.push(`${r.job} failed ${formatTime(r.stored_at)}${r.error_code?` (${r.error_code})`:""}.`); if(daily.rejected) alerts.push(`${number(daily.rejected)} rows were rejected in the last 24 hours.`); byId("quality").innerHTML=(alerts.length?alerts:["No defensible quality alerts in current diagnostics."]).map(x=>`<li>${escape(x)}</li>`).join("");
}
function details(row) { return `<dl class="details-grid">${[["Source observation key",row.source_observation_key],["Logical key",row.logical_key],["Source identifier",row.source_identifier],["Station",row.source_station_id||row.station_id],["Configuration version",row.source_configuration_version],["Fetched",formatTime(row.fetched_at)],["Stored",formatTime(row.stored_at)],["Timestamp basis",timestampLabel(row)],["Attribution",row.beach_id ? "Beach-attributed copy; physical identity is the source observation key." : "Physical source observation"]].map(([a,b])=>`<div><dt>${a}</dt><dd>${escape(b||"Not available")}</dd></div>`).join("")}</dl>`; }
async function loadObservations(cursor = null) { controller?.abort(); controller=new AbortController(); byId("observations-loading").hidden=false; try { const data=await requestJson(observationQuery(formValues(),cursor),controller.signal); nextCursor=data.nextCursor; byId("next").disabled=!data.hasMore; byId("previous").disabled=page===0; byId("result-count").textContent=`Page ${page+1} · ${data.rows.length} rows`; byId("observations").innerHTML=data.rows.map((r,i)=>`<tr><td><strong>${escape(r.value_numeric ?? r.value_text)}</strong>${escape(r.unit||"")}</td><td>${escape(DATASET_NAMES[r.observation_type]||r.observation_type)}</td><td>${escape(r.beach_id||"Physical only")}<br>${escape(AREA_NAMES[r.beach_area]||r.beach_area||"")}</td><td>${escape(r.provider)}<br>${escape(r.source_station_id||r.station_id||"")}</td><td><strong>${timestampLabel(r)}</strong>${formatTime(r.observed_at)}</td><td>${formatTime(r.stored_at)}</td><td>${r.revision_number}${r.has_revision_history?" · history":""}</td><td>${escape(r.freshness_state||"Unknown")}<br>${escape(r.quality_flag||"No flag")}</td><td><button class="text-button details-toggle" type="button" aria-expanded="false" aria-controls="details-${i}">Show</button></td></tr><tr id="details-${i}" class="details-row" hidden><td colspan="9">${details(r)}</td></tr>`).join("")||`<tr><td colspan="9">No observations match these filters.</td></tr>`; } catch(error) { if(error.name!=="AbortError") { byId("error").textContent=error.message; byId("error").hidden=false; } } finally { byId("observations-loading").hidden=true; } }
async function load() { byId("error").hidden=true; try { const data=await requestJson(SUMMARY_ENDPOINT); renderSummary(data); byId("loading").hidden=true; byId("dashboard").hidden=false; await loadObservations(); } catch(error) { byId("loading").hidden=true; byId("error").textContent=error.message; byId("error").hidden=false; } }
for(const [value,label] of Object.entries(DATASET_NAMES)) byId("filters").elements.type.add(new Option(label,value)); for(const [value,label] of Object.entries(AREA_NAMES)) byId("filters").elements.area.add(new Option(label,value));
byId("filters").addEventListener("submit",e=>{e.preventDefault(); page=0;cursors=[null];loadObservations();}); byId("clear").addEventListener("click",()=>setTimeout(()=>{page=0;cursors=[null];loadObservations();})); byId("next").addEventListener("click",()=>{cursors.push(nextCursor);page++;loadObservations(nextCursor);}); byId("previous").addEventListener("click",()=>{cursors.pop();page--;loadObservations(cursors.at(-1));}); byId("observations").addEventListener("click",e=>{const b=e.target.closest(".details-toggle");if(!b)return;const row=byId(b.getAttribute("aria-controls"));const open=b.getAttribute("aria-expanded")==="true";b.setAttribute("aria-expanded",String(!open));b.textContent=open?"Show":"Hide";row.hidden=open;}); byId("refresh").addEventListener("click",load); load();
