export const VERIFICATION_ENDPOINT = "/admin/service/admin/verification";
export const LOCATION_NAMES = { "gulf-shores-public-beach": "Gulf Shores Public Beach", "gulf-state-park-pavilion": "Gulf State Park Pavilion", "little-lagoon-pass": "Little Lagoon Pass", "cotton-bayou": "Cotton Bayou", "alabama-point": "Alabama Point", "florida-point": "Florida Point" };
export { formatCentralTime as formatDate } from "../shared.js";
export function formatDuration(value) { return Number.isFinite(value) ? value < 1000 ? `${value} ms` : `${(value / 1000).toFixed(1)} sec` : "Not available"; }
export function statusLabel(value) { return ({ pass: "Passing", warning: "Warning", fail: "Failed", unavailable: "Unavailable" })[value] || "Unavailable"; }
export function historyMatches(item, { status = "", verifierId = "", search = "" } = {}) { if (status && item.status !== status) return false; if (verifierId && item.verifierId !== verifierId) return false; const query = search.trim().toLowerCase(); if (!query) return true; return [item.verifierId, item.verifierName, item.slot, item.reason, ...(item.locations || []).flatMap((location) => [location.name, location.message]), ...(item.checks || []).flatMap((check) => [check.name, check.provider, check.location, check.expectedValue, check.actualValue, check.message])].filter(Boolean).join(" ").toLowerCase().includes(query); }
export function fleetHistory(data) { return (data.verifiers || []).flatMap((verifier) => (verifier.history || []).map((report) => ({ ...report, verifierId: verifier.id, verifierName: verifier.displayName }))).sort((a, b) => String(b.completedAt).localeCompare(String(a.completedAt))); }
export function failureMessage({ status = 0, redirected = false, contentType = "", network = false } = {}) { if (network || redirected || status === 401 || status === 403 || !contentType.includes("application/json")) return "Your admin Access session may have expired. Re-authenticate and refresh this page."; return "Verification data could not be refreshed. The last successful state remains visible."; }
export function pollController({ refresh, documentRef = document, intervalMs = 60000, timers = globalThis }) { let timer = null; const stop = () => { if (timer !== null) timers.clearInterval(timer); timer = null; }; const start = () => { stop(); if (!documentRef.hidden) timer = timers.setInterval(refresh, intervalMs); }; const visibility = () => documentRef.hidden ? stop() : (refresh(), start()); documentRef.addEventListener("visibilitychange", visibility); start(); return { stop() { stop(); documentRef.removeEventListener("visibilitychange", visibility); }, isRunning: () => timer !== null }; }
