import { VERIFICATION_ENDPOINT, failureMessage, formatDate, formatDuration, historyMatches, pollController, statusLabel } from "./core.js?v=1";
const $ = (selector) => document.querySelector(selector); let lastData = null, refreshing = false, hadError = false, selectedStatus = "";
const empty = (message) => { const node = document.createElement("div"); node.className = "empty"; node.textContent = message; return node; };
const title = (value) => String(value || "unknown").replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const addDetail = (list, label, value) => { const dt = document.createElement("dt"), dd = document.createElement("dd"); dt.textContent = label; dd.textContent = value ?? "Not available"; list.append(dt, dd); };
const pill = (status) => { const node = document.createElement("span"); node.className = "badge status-badge"; node.dataset.status = status; node.textContent = statusLabel(status); return node; };

function renderOverall(data) { const status = $("#overall-status"); status.textContent = statusLabel(data.summary.overallStatus); status.dataset.status = data.summary.overallStatus; const metrics = $("#overall-metrics"); metrics.replaceChildren(); [["Current coverage", data.summary.coverageLabel], ["Latest verification", formatDate(data.summary.lastVerificationAt)], ["Latest scheduled slot", data.summary.latestSlot || "Not available"], ["Last successful verification", formatDate(data.summary.lastSuccessfulVerificationAt)], ["Next expected verification", data.summary.nextExpectedSlot || "Not available"], ["Alerting", data.summary.alertingEnabled ? "Enabled" : "Disabled"]].forEach(([label, value]) => { const box = document.createElement("div"); addDetail(box, label, value); metrics.append(box); }); }
function renderLatest(report) { const target = $("#latest"); target.replaceChildren(); $("#latest-badge").replaceWith(Object.assign(pill(report?.status ?? "unavailable"), { id: "latest-badge" })); if (!report) { target.append(empty("No verification report has been persisted yet.")); return; } const list = document.createElement("dl"); list.className = "report-details"; [["Reason", report.reason || "No warning or failure reason"], ["Scheduled slot", report.slot], ["Started", formatDate(report.startedAt)], ["Completed", formatDate(report.completedAt)], ["Duration", formatDuration(report.durationMs)], ["Alert outcome", report.wouldAlert ? "Would alert" : "Would not alert"], ["Official source observation", formatDate(report.officialSource?.observedAt, "Not recorded by report v1")], ["Published API observation", formatDate(report.publishedResult?.fetchedAt, "Not recorded by report v1")]].forEach(([label, value]) => addDetail(list, label, value)); target.append(list); }
function renderLocations(report) { const target = $("#locations"); target.replaceChildren(); if (!report?.locations?.length) { target.append(empty("No location comparison is available.")); return; } report.locations.forEach((item) => { const card = document.createElement("article"); card.className = "location-card"; card.dataset.status = item.status; const heading = document.createElement("div"); heading.className = "card-top"; const name = document.createElement("h3"); name.textContent = item.name; heading.append(name, pill(item.status)); const list = document.createElement("dl"); list.className = "detail-list"; [["Official flag", item.officialFlag], ["Published flag", item.publishedFlag], ["Official purple advisory", item.officialPurple === null ? null : item.officialPurple ? "Yes" : "No"], ["Published purple advisory", item.publishedPurple === null ? null : item.publishedPurple ? "Yes" : "No"], ["Match", item.matches ? "Match" : "Does not match"]].forEach(([label, value]) => addDetail(list, label, value)); card.append(heading, list); if (item.message) { const message = document.createElement("p"); message.className = "result-message"; message.textContent = item.message; card.append(message); } target.append(card); }); }
function renderChecks(report) { const target = $("#checks"); target.replaceChildren(); if (!report?.checks?.length) { target.append(empty("No check results are available.")); return; } report.checks.forEach((item) => { const row = document.createElement("article"); row.className = "check-row"; const heading = document.createElement("h3"); heading.textContent = title(item.name); const message = document.createElement("p"); message.textContent = item.message; row.append(pill(item.status), heading, message); target.append(row); }); }
function renderHistory(data) { const target = $("#history"); target.replaceChildren(); const filtered = data.history.filter((item) => historyMatches(item, { status: selectedStatus, search: $("#history-search").value })); $("#history-count").textContent = `${filtered.length} of ${data.history.length}`; if (!filtered.length) { target.append(empty(data.history.length ? "No reports match the selected filters." : "No verification history is available.")); return; } filtered.forEach((item) => { const details = document.createElement("details"); details.className = "history-row"; const summary = document.createElement("summary"); const main = document.createElement("span"); main.innerHTML = `<strong></strong><small></small>`; main.querySelector("strong").textContent = formatDate(item.completedAt); main.querySelector("small").textContent = `${item.slot} · ${item.reason || "No issue recorded"}`; const meta = document.createElement("span"); meta.className = "history-meta"; meta.append(pill(item.status), document.createTextNode(`${item.coverageCount} locations · ${formatDuration(item.durationMs)}`)); summary.append(main, meta); const body = document.createElement("div"); body.className = "history-body"; const locationText = document.createElement("p"); locationText.textContent = item.locations.map((location) => `${location.name}: ${statusLabel(location.status)}`).join(" · "); const checkText = document.createElement("p"); checkText.textContent = item.checks.map((check) => `${title(check.name)}: ${check.message}`).join(" · "); body.append(locationText, checkText); details.append(summary, body); target.append(details); }); }
function renderCoverage(data) { const target = $("#coverage"); target.replaceChildren(); data.coverage.forEach((item) => { const row = document.createElement("article"); row.className = "coverage-row"; const heading = document.createElement("h3"); heading.textContent = item.domain; const badge = document.createElement("span"); badge.className = "badge"; badge.textContent = title(item.status); const text = document.createElement("p"); text.textContent = item.description; row.append(heading, badge, text); target.append(row); }); }
function renderAlerts(data) { const target = $("#alert-status"); target.replaceChildren(); const list = document.createElement("dl"); list.className = "report-details"; addDetail(list, "Verification alerting", data.summary.alertingEnabled ? "Enabled" : "Disabled"); addDetail(list, "Latest report", data.latest?.wouldAlert ? "Would alert" : data.latest ? "Would not alert" : "No report available"); addDetail(list, "Recent alert-related status", data.latest ? `${statusLabel(data.latest.status)} at ${formatDate(data.latest.completedAt)}` : "Not available"); target.append(list); }
function render(data) { lastData = data; renderOverall(data); renderLatest(data.latest); renderLocations(data.latest); renderChecks(data.latest); renderHistory(data); renderCoverage(data); renderAlerts(data); $("#updated-label").textContent = `Updated ${formatDate(data.generatedAt)}`; $("#loading").hidden = true; $("#dashboard").hidden = false; }
async function refresh({ announce = false } = {}) { if (refreshing) return; refreshing = true; $("#refresh").disabled = true; try { const response = await fetch(VERIFICATION_ENDPOINT, { credentials: "include", cache: "no-store", headers: { Accept: "application/json" } }); const contentType = response.headers.get("content-type") || ""; if (!response.ok || response.redirected || !contentType.includes("application/json")) throw new Error(failureMessage({ status: response.status, redirected: response.redirected, contentType })); const data = await response.json(); render(data); $("#refresh-error").hidden = true; if (hadError) $("#announcer").textContent = "Verification updates have resumed."; else if (announce) $("#announcer").textContent = "Verification data refreshed."; hadError = false; } catch (error) { const box = $("#refresh-error"); box.textContent = error instanceof Error && /session/i.test(error.message) ? error.message : failureMessage({ network: true }); box.hidden = false; hadError = true; if (!lastData) { $("#loading").hidden = true; $("#dashboard").hidden = false; render({ generatedAt: null, summary: { overallStatus: "unavailable", coverageLabel: "Gulf Shores flags", alertingEnabled: false }, latest: null, history: [], coverage: [] }); } } finally { refreshing = false; $("#refresh").disabled = false; } }
$("#filters").addEventListener("click", (event) => { const button = event.target.closest("button[data-status]"); if (!button) return; selectedStatus = button.dataset.status; document.querySelectorAll("[data-status][aria-pressed]").forEach((item) => item.setAttribute("aria-pressed", String(item === button))); if (lastData) renderHistory(lastData); });
$("#history-search").addEventListener("input", () => { if (lastData) renderHistory(lastData); }); $("#refresh").addEventListener("click", () => refresh({ announce: true }));
refresh(); pollController({ refresh });
